# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1082/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1082/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sid/CLionProjects/miniRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sid/CLionProjects/miniRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1082/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1082/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sid/CLionProjects/miniRT/CMakeFiles /home/sid/CLionProjects/miniRT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sid/CLionProjects/miniRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named miniRT

# Build rule for target.
miniRT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miniRT
.PHONY : miniRT

# fast build rule for target.
miniRT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/build
.PHONY : miniRT/fast

libft/free_array.o: libft/free_array.c.o
.PHONY : libft/free_array.o

# target to build an object file
libft/free_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/free_array.c.o
.PHONY : libft/free_array.c.o

libft/free_array.i: libft/free_array.c.i
.PHONY : libft/free_array.i

# target to preprocess a source file
libft/free_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/free_array.c.i
.PHONY : libft/free_array.c.i

libft/free_array.s: libft/free_array.c.s
.PHONY : libft/free_array.s

# target to generate assembly for a file
libft/free_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/free_array.c.s
.PHONY : libft/free_array.c.s

libft/ft_atod.o: libft/ft_atod.c.o
.PHONY : libft/ft_atod.o

# target to build an object file
libft/ft_atod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atod.c.o
.PHONY : libft/ft_atod.c.o

libft/ft_atod.i: libft/ft_atod.c.i
.PHONY : libft/ft_atod.i

# target to preprocess a source file
libft/ft_atod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atod.c.i
.PHONY : libft/ft_atod.c.i

libft/ft_atod.s: libft/ft_atod.c.s
.PHONY : libft/ft_atod.s

# target to generate assembly for a file
libft/ft_atod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atod.c.s
.PHONY : libft/ft_atod.c.s

libft/ft_atoi.o: libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.o

# target to build an object file
libft/ft_atoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.c.o

libft/ft_atoi.i: libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.i

# target to preprocess a source file
libft/ft_atoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.c.i

libft/ft_atoi.s: libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.s

# target to generate assembly for a file
libft/ft_atoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.c.s

libft/ft_bzero.o: libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.o

# target to build an object file
libft/ft_bzero.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.c.o

libft/ft_bzero.i: libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.i

# target to preprocess a source file
libft/ft_bzero.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.c.i

libft/ft_bzero.s: libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.s

# target to generate assembly for a file
libft/ft_bzero.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.c.s

libft/ft_calloc.o: libft/ft_calloc.c.o
.PHONY : libft/ft_calloc.o

# target to build an object file
libft/ft_calloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_calloc.c.o
.PHONY : libft/ft_calloc.c.o

libft/ft_calloc.i: libft/ft_calloc.c.i
.PHONY : libft/ft_calloc.i

# target to preprocess a source file
libft/ft_calloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_calloc.c.i
.PHONY : libft/ft_calloc.c.i

libft/ft_calloc.s: libft/ft_calloc.c.s
.PHONY : libft/ft_calloc.s

# target to generate assembly for a file
libft/ft_calloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_calloc.c.s
.PHONY : libft/ft_calloc.c.s

libft/ft_contains.o: libft/ft_contains.c.o
.PHONY : libft/ft_contains.o

# target to build an object file
libft/ft_contains.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_contains.c.o
.PHONY : libft/ft_contains.c.o

libft/ft_contains.i: libft/ft_contains.c.i
.PHONY : libft/ft_contains.i

# target to preprocess a source file
libft/ft_contains.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_contains.c.i
.PHONY : libft/ft_contains.c.i

libft/ft_contains.s: libft/ft_contains.c.s
.PHONY : libft/ft_contains.s

# target to generate assembly for a file
libft/ft_contains.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_contains.c.s
.PHONY : libft/ft_contains.c.s

libft/ft_ends_with.o: libft/ft_ends_with.c.o
.PHONY : libft/ft_ends_with.o

# target to build an object file
libft/ft_ends_with.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_ends_with.c.o
.PHONY : libft/ft_ends_with.c.o

libft/ft_ends_with.i: libft/ft_ends_with.c.i
.PHONY : libft/ft_ends_with.i

# target to preprocess a source file
libft/ft_ends_with.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_ends_with.c.i
.PHONY : libft/ft_ends_with.c.i

libft/ft_ends_with.s: libft/ft_ends_with.c.s
.PHONY : libft/ft_ends_with.s

# target to generate assembly for a file
libft/ft_ends_with.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_ends_with.c.s
.PHONY : libft/ft_ends_with.c.s

libft/ft_isalnum.o: libft/ft_isalnum.c.o
.PHONY : libft/ft_isalnum.o

# target to build an object file
libft/ft_isalnum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalnum.c.o
.PHONY : libft/ft_isalnum.c.o

libft/ft_isalnum.i: libft/ft_isalnum.c.i
.PHONY : libft/ft_isalnum.i

# target to preprocess a source file
libft/ft_isalnum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalnum.c.i
.PHONY : libft/ft_isalnum.c.i

libft/ft_isalnum.s: libft/ft_isalnum.c.s
.PHONY : libft/ft_isalnum.s

# target to generate assembly for a file
libft/ft_isalnum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalnum.c.s
.PHONY : libft/ft_isalnum.c.s

libft/ft_isalpha.o: libft/ft_isalpha.c.o
.PHONY : libft/ft_isalpha.o

# target to build an object file
libft/ft_isalpha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalpha.c.o
.PHONY : libft/ft_isalpha.c.o

libft/ft_isalpha.i: libft/ft_isalpha.c.i
.PHONY : libft/ft_isalpha.i

# target to preprocess a source file
libft/ft_isalpha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalpha.c.i
.PHONY : libft/ft_isalpha.c.i

libft/ft_isalpha.s: libft/ft_isalpha.c.s
.PHONY : libft/ft_isalpha.s

# target to generate assembly for a file
libft/ft_isalpha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isalpha.c.s
.PHONY : libft/ft_isalpha.c.s

libft/ft_isascii.o: libft/ft_isascii.c.o
.PHONY : libft/ft_isascii.o

# target to build an object file
libft/ft_isascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isascii.c.o
.PHONY : libft/ft_isascii.c.o

libft/ft_isascii.i: libft/ft_isascii.c.i
.PHONY : libft/ft_isascii.i

# target to preprocess a source file
libft/ft_isascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isascii.c.i
.PHONY : libft/ft_isascii.c.i

libft/ft_isascii.s: libft/ft_isascii.c.s
.PHONY : libft/ft_isascii.s

# target to generate assembly for a file
libft/ft_isascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isascii.c.s
.PHONY : libft/ft_isascii.c.s

libft/ft_isdigit.o: libft/ft_isdigit.c.o
.PHONY : libft/ft_isdigit.o

# target to build an object file
libft/ft_isdigit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isdigit.c.o
.PHONY : libft/ft_isdigit.c.o

libft/ft_isdigit.i: libft/ft_isdigit.c.i
.PHONY : libft/ft_isdigit.i

# target to preprocess a source file
libft/ft_isdigit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isdigit.c.i
.PHONY : libft/ft_isdigit.c.i

libft/ft_isdigit.s: libft/ft_isdigit.c.s
.PHONY : libft/ft_isdigit.s

# target to generate assembly for a file
libft/ft_isdigit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isdigit.c.s
.PHONY : libft/ft_isdigit.c.s

libft/ft_isprint.o: libft/ft_isprint.c.o
.PHONY : libft/ft_isprint.o

# target to build an object file
libft/ft_isprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isprint.c.o
.PHONY : libft/ft_isprint.c.o

libft/ft_isprint.i: libft/ft_isprint.c.i
.PHONY : libft/ft_isprint.i

# target to preprocess a source file
libft/ft_isprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isprint.c.i
.PHONY : libft/ft_isprint.c.i

libft/ft_isprint.s: libft/ft_isprint.c.s
.PHONY : libft/ft_isprint.s

# target to generate assembly for a file
libft/ft_isprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_isprint.c.s
.PHONY : libft/ft_isprint.c.s

libft/ft_iswhite_space.o: libft/ft_iswhite_space.c.o
.PHONY : libft/ft_iswhite_space.o

# target to build an object file
libft/ft_iswhite_space.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_iswhite_space.c.o
.PHONY : libft/ft_iswhite_space.c.o

libft/ft_iswhite_space.i: libft/ft_iswhite_space.c.i
.PHONY : libft/ft_iswhite_space.i

# target to preprocess a source file
libft/ft_iswhite_space.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_iswhite_space.c.i
.PHONY : libft/ft_iswhite_space.c.i

libft/ft_iswhite_space.s: libft/ft_iswhite_space.c.s
.PHONY : libft/ft_iswhite_space.s

# target to generate assembly for a file
libft/ft_iswhite_space.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_iswhite_space.c.s
.PHONY : libft/ft_iswhite_space.c.s

libft/ft_itoa.o: libft/ft_itoa.c.o
.PHONY : libft/ft_itoa.o

# target to build an object file
libft/ft_itoa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_itoa.c.o
.PHONY : libft/ft_itoa.c.o

libft/ft_itoa.i: libft/ft_itoa.c.i
.PHONY : libft/ft_itoa.i

# target to preprocess a source file
libft/ft_itoa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_itoa.c.i
.PHONY : libft/ft_itoa.c.i

libft/ft_itoa.s: libft/ft_itoa.c.s
.PHONY : libft/ft_itoa.s

# target to generate assembly for a file
libft/ft_itoa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_itoa.c.s
.PHONY : libft/ft_itoa.c.s

libft/ft_memchr.o: libft/ft_memchr.c.o
.PHONY : libft/ft_memchr.o

# target to build an object file
libft/ft_memchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memchr.c.o
.PHONY : libft/ft_memchr.c.o

libft/ft_memchr.i: libft/ft_memchr.c.i
.PHONY : libft/ft_memchr.i

# target to preprocess a source file
libft/ft_memchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memchr.c.i
.PHONY : libft/ft_memchr.c.i

libft/ft_memchr.s: libft/ft_memchr.c.s
.PHONY : libft/ft_memchr.s

# target to generate assembly for a file
libft/ft_memchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memchr.c.s
.PHONY : libft/ft_memchr.c.s

libft/ft_memcmp.o: libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.o

# target to build an object file
libft/ft_memcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.c.o

libft/ft_memcmp.i: libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.i

# target to preprocess a source file
libft/ft_memcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.c.i

libft/ft_memcmp.s: libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.s

# target to generate assembly for a file
libft/ft_memcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.c.s

libft/ft_memcpy.o: libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.o

# target to build an object file
libft/ft_memcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.c.o

libft/ft_memcpy.i: libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.i

# target to preprocess a source file
libft/ft_memcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.c.i

libft/ft_memcpy.s: libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.s

# target to generate assembly for a file
libft/ft_memcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.c.s

libft/ft_memmove.o: libft/ft_memmove.c.o
.PHONY : libft/ft_memmove.o

# target to build an object file
libft/ft_memmove.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memmove.c.o
.PHONY : libft/ft_memmove.c.o

libft/ft_memmove.i: libft/ft_memmove.c.i
.PHONY : libft/ft_memmove.i

# target to preprocess a source file
libft/ft_memmove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memmove.c.i
.PHONY : libft/ft_memmove.c.i

libft/ft_memmove.s: libft/ft_memmove.c.s
.PHONY : libft/ft_memmove.s

# target to generate assembly for a file
libft/ft_memmove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memmove.c.s
.PHONY : libft/ft_memmove.c.s

libft/ft_memset.o: libft/ft_memset.c.o
.PHONY : libft/ft_memset.o

# target to build an object file
libft/ft_memset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memset.c.o
.PHONY : libft/ft_memset.c.o

libft/ft_memset.i: libft/ft_memset.c.i
.PHONY : libft/ft_memset.i

# target to preprocess a source file
libft/ft_memset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memset.c.i
.PHONY : libft/ft_memset.c.i

libft/ft_memset.s: libft/ft_memset.c.s
.PHONY : libft/ft_memset.s

# target to generate assembly for a file
libft/ft_memset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_memset.c.s
.PHONY : libft/ft_memset.c.s

libft/ft_printf/ft_printf.o: libft/ft_printf/ft_printf.c.o
.PHONY : libft/ft_printf/ft_printf.o

# target to build an object file
libft/ft_printf/ft_printf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/ft_printf.c.o
.PHONY : libft/ft_printf/ft_printf.c.o

libft/ft_printf/ft_printf.i: libft/ft_printf/ft_printf.c.i
.PHONY : libft/ft_printf/ft_printf.i

# target to preprocess a source file
libft/ft_printf/ft_printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/ft_printf.c.i
.PHONY : libft/ft_printf/ft_printf.c.i

libft/ft_printf/ft_printf.s: libft/ft_printf/ft_printf.c.s
.PHONY : libft/ft_printf/ft_printf.s

# target to generate assembly for a file
libft/ft_printf/ft_printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/ft_printf.c.s
.PHONY : libft/ft_printf/ft_printf.c.s

libft/ft_printf/hex.o: libft/ft_printf/hex.c.o
.PHONY : libft/ft_printf/hex.o

# target to build an object file
libft/ft_printf/hex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex.c.o
.PHONY : libft/ft_printf/hex.c.o

libft/ft_printf/hex.i: libft/ft_printf/hex.c.i
.PHONY : libft/ft_printf/hex.i

# target to preprocess a source file
libft/ft_printf/hex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex.c.i
.PHONY : libft/ft_printf/hex.c.i

libft/ft_printf/hex.s: libft/ft_printf/hex.c.s
.PHONY : libft/ft_printf/hex.s

# target to generate assembly for a file
libft/ft_printf/hex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex.c.s
.PHONY : libft/ft_printf/hex.c.s

libft/ft_printf/hex_util.o: libft/ft_printf/hex_util.c.o
.PHONY : libft/ft_printf/hex_util.o

# target to build an object file
libft/ft_printf/hex_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex_util.c.o
.PHONY : libft/ft_printf/hex_util.c.o

libft/ft_printf/hex_util.i: libft/ft_printf/hex_util.c.i
.PHONY : libft/ft_printf/hex_util.i

# target to preprocess a source file
libft/ft_printf/hex_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex_util.c.i
.PHONY : libft/ft_printf/hex_util.c.i

libft/ft_printf/hex_util.s: libft/ft_printf/hex_util.c.s
.PHONY : libft/ft_printf/hex_util.s

# target to generate assembly for a file
libft/ft_printf/hex_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/hex_util.c.s
.PHONY : libft/ft_printf/hex_util.c.s

libft/ft_printf/printing.o: libft/ft_printf/printing.c.o
.PHONY : libft/ft_printf/printing.o

# target to build an object file
libft/ft_printf/printing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/printing.c.o
.PHONY : libft/ft_printf/printing.c.o

libft/ft_printf/printing.i: libft/ft_printf/printing.c.i
.PHONY : libft/ft_printf/printing.i

# target to preprocess a source file
libft/ft_printf/printing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/printing.c.i
.PHONY : libft/ft_printf/printing.c.i

libft/ft_printf/printing.s: libft/ft_printf/printing.c.s
.PHONY : libft/ft_printf/printing.s

# target to generate assembly for a file
libft/ft_printf/printing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_printf/printing.c.s
.PHONY : libft/ft_printf/printing.c.s

libft/ft_putchar_fd.o: libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.o

# target to build an object file
libft/ft_putchar_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.c.o

libft/ft_putchar_fd.i: libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.i

# target to preprocess a source file
libft/ft_putchar_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.c.i

libft/ft_putchar_fd.s: libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.s

# target to generate assembly for a file
libft/ft_putchar_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.c.s

libft/ft_putendl_fd.o: libft/ft_putendl_fd.c.o
.PHONY : libft/ft_putendl_fd.o

# target to build an object file
libft/ft_putendl_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putendl_fd.c.o
.PHONY : libft/ft_putendl_fd.c.o

libft/ft_putendl_fd.i: libft/ft_putendl_fd.c.i
.PHONY : libft/ft_putendl_fd.i

# target to preprocess a source file
libft/ft_putendl_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putendl_fd.c.i
.PHONY : libft/ft_putendl_fd.c.i

libft/ft_putendl_fd.s: libft/ft_putendl_fd.c.s
.PHONY : libft/ft_putendl_fd.s

# target to generate assembly for a file
libft/ft_putendl_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putendl_fd.c.s
.PHONY : libft/ft_putendl_fd.c.s

libft/ft_putnbr_fd.o: libft/ft_putnbr_fd.c.o
.PHONY : libft/ft_putnbr_fd.o

# target to build an object file
libft/ft_putnbr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putnbr_fd.c.o
.PHONY : libft/ft_putnbr_fd.c.o

libft/ft_putnbr_fd.i: libft/ft_putnbr_fd.c.i
.PHONY : libft/ft_putnbr_fd.i

# target to preprocess a source file
libft/ft_putnbr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putnbr_fd.c.i
.PHONY : libft/ft_putnbr_fd.c.i

libft/ft_putnbr_fd.s: libft/ft_putnbr_fd.c.s
.PHONY : libft/ft_putnbr_fd.s

# target to generate assembly for a file
libft/ft_putnbr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putnbr_fd.c.s
.PHONY : libft/ft_putnbr_fd.c.s

libft/ft_putstr_fd.o: libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.o

# target to build an object file
libft/ft_putstr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.c.o

libft/ft_putstr_fd.i: libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.i

# target to preprocess a source file
libft/ft_putstr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.c.i

libft/ft_putstr_fd.s: libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.s

# target to generate assembly for a file
libft/ft_putstr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.c.s

libft/ft_split.o: libft/ft_split.c.o
.PHONY : libft/ft_split.o

# target to build an object file
libft/ft_split.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_split.c.o
.PHONY : libft/ft_split.c.o

libft/ft_split.i: libft/ft_split.c.i
.PHONY : libft/ft_split.i

# target to preprocess a source file
libft/ft_split.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_split.c.i
.PHONY : libft/ft_split.c.i

libft/ft_split.s: libft/ft_split.c.s
.PHONY : libft/ft_split.s

# target to generate assembly for a file
libft/ft_split.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_split.c.s
.PHONY : libft/ft_split.c.s

libft/ft_starts_with.o: libft/ft_starts_with.c.o
.PHONY : libft/ft_starts_with.o

# target to build an object file
libft/ft_starts_with.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_starts_with.c.o
.PHONY : libft/ft_starts_with.c.o

libft/ft_starts_with.i: libft/ft_starts_with.c.i
.PHONY : libft/ft_starts_with.i

# target to preprocess a source file
libft/ft_starts_with.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_starts_with.c.i
.PHONY : libft/ft_starts_with.c.i

libft/ft_starts_with.s: libft/ft_starts_with.c.s
.PHONY : libft/ft_starts_with.s

# target to generate assembly for a file
libft/ft_starts_with.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_starts_with.c.s
.PHONY : libft/ft_starts_with.c.s

libft/ft_strchr.o: libft/ft_strchr.c.o
.PHONY : libft/ft_strchr.o

# target to build an object file
libft/ft_strchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strchr.c.o
.PHONY : libft/ft_strchr.c.o

libft/ft_strchr.i: libft/ft_strchr.c.i
.PHONY : libft/ft_strchr.i

# target to preprocess a source file
libft/ft_strchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strchr.c.i
.PHONY : libft/ft_strchr.c.i

libft/ft_strchr.s: libft/ft_strchr.c.s
.PHONY : libft/ft_strchr.s

# target to generate assembly for a file
libft/ft_strchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strchr.c.s
.PHONY : libft/ft_strchr.c.s

libft/ft_strdup.o: libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.o

# target to build an object file
libft/ft_strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.c.o

libft/ft_strdup.i: libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.i

# target to preprocess a source file
libft/ft_strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.c.i

libft/ft_strdup.s: libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.s

# target to generate assembly for a file
libft/ft_strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.c.s

libft/ft_streq.o: libft/ft_streq.c.o
.PHONY : libft/ft_streq.o

# target to build an object file
libft/ft_streq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_streq.c.o
.PHONY : libft/ft_streq.c.o

libft/ft_streq.i: libft/ft_streq.c.i
.PHONY : libft/ft_streq.i

# target to preprocess a source file
libft/ft_streq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_streq.c.i
.PHONY : libft/ft_streq.c.i

libft/ft_streq.s: libft/ft_streq.c.s
.PHONY : libft/ft_streq.s

# target to generate assembly for a file
libft/ft_streq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_streq.c.s
.PHONY : libft/ft_streq.c.s

libft/ft_striteri.o: libft/ft_striteri.c.o
.PHONY : libft/ft_striteri.o

# target to build an object file
libft/ft_striteri.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_striteri.c.o
.PHONY : libft/ft_striteri.c.o

libft/ft_striteri.i: libft/ft_striteri.c.i
.PHONY : libft/ft_striteri.i

# target to preprocess a source file
libft/ft_striteri.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_striteri.c.i
.PHONY : libft/ft_striteri.c.i

libft/ft_striteri.s: libft/ft_striteri.c.s
.PHONY : libft/ft_striteri.s

# target to generate assembly for a file
libft/ft_striteri.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_striteri.c.s
.PHONY : libft/ft_striteri.c.s

libft/ft_strjoin.o: libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.o

# target to build an object file
libft/ft_strjoin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.c.o

libft/ft_strjoin.i: libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.i

# target to preprocess a source file
libft/ft_strjoin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.c.i

libft/ft_strjoin.s: libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.s

# target to generate assembly for a file
libft/ft_strjoin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.c.s

libft/ft_strlcat.o: libft/ft_strlcat.c.o
.PHONY : libft/ft_strlcat.o

# target to build an object file
libft/ft_strlcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcat.c.o
.PHONY : libft/ft_strlcat.c.o

libft/ft_strlcat.i: libft/ft_strlcat.c.i
.PHONY : libft/ft_strlcat.i

# target to preprocess a source file
libft/ft_strlcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcat.c.i
.PHONY : libft/ft_strlcat.c.i

libft/ft_strlcat.s: libft/ft_strlcat.c.s
.PHONY : libft/ft_strlcat.s

# target to generate assembly for a file
libft/ft_strlcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcat.c.s
.PHONY : libft/ft_strlcat.c.s

libft/ft_strlcpy.o: libft/ft_strlcpy.c.o
.PHONY : libft/ft_strlcpy.o

# target to build an object file
libft/ft_strlcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcpy.c.o
.PHONY : libft/ft_strlcpy.c.o

libft/ft_strlcpy.i: libft/ft_strlcpy.c.i
.PHONY : libft/ft_strlcpy.i

# target to preprocess a source file
libft/ft_strlcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcpy.c.i
.PHONY : libft/ft_strlcpy.c.i

libft/ft_strlcpy.s: libft/ft_strlcpy.c.s
.PHONY : libft/ft_strlcpy.s

# target to generate assembly for a file
libft/ft_strlcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlcpy.c.s
.PHONY : libft/ft_strlcpy.c.s

libft/ft_strlen.o: libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.o

# target to build an object file
libft/ft_strlen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.c.o

libft/ft_strlen.i: libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.i

# target to preprocess a source file
libft/ft_strlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.c.i

libft/ft_strlen.s: libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.s

# target to generate assembly for a file
libft/ft_strlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.c.s

libft/ft_strmapi.o: libft/ft_strmapi.c.o
.PHONY : libft/ft_strmapi.o

# target to build an object file
libft/ft_strmapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strmapi.c.o
.PHONY : libft/ft_strmapi.c.o

libft/ft_strmapi.i: libft/ft_strmapi.c.i
.PHONY : libft/ft_strmapi.i

# target to preprocess a source file
libft/ft_strmapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strmapi.c.i
.PHONY : libft/ft_strmapi.c.i

libft/ft_strmapi.s: libft/ft_strmapi.c.s
.PHONY : libft/ft_strmapi.s

# target to generate assembly for a file
libft/ft_strmapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strmapi.c.s
.PHONY : libft/ft_strmapi.c.s

libft/ft_strncmp.o: libft/ft_strncmp.c.o
.PHONY : libft/ft_strncmp.o

# target to build an object file
libft/ft_strncmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strncmp.c.o
.PHONY : libft/ft_strncmp.c.o

libft/ft_strncmp.i: libft/ft_strncmp.c.i
.PHONY : libft/ft_strncmp.i

# target to preprocess a source file
libft/ft_strncmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strncmp.c.i
.PHONY : libft/ft_strncmp.c.i

libft/ft_strncmp.s: libft/ft_strncmp.c.s
.PHONY : libft/ft_strncmp.s

# target to generate assembly for a file
libft/ft_strncmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strncmp.c.s
.PHONY : libft/ft_strncmp.c.s

libft/ft_strnstr.o: libft/ft_strnstr.c.o
.PHONY : libft/ft_strnstr.o

# target to build an object file
libft/ft_strnstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strnstr.c.o
.PHONY : libft/ft_strnstr.c.o

libft/ft_strnstr.i: libft/ft_strnstr.c.i
.PHONY : libft/ft_strnstr.i

# target to preprocess a source file
libft/ft_strnstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strnstr.c.i
.PHONY : libft/ft_strnstr.c.i

libft/ft_strnstr.s: libft/ft_strnstr.c.s
.PHONY : libft/ft_strnstr.s

# target to generate assembly for a file
libft/ft_strnstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strnstr.c.s
.PHONY : libft/ft_strnstr.c.s

libft/ft_strrchr.o: libft/ft_strrchr.c.o
.PHONY : libft/ft_strrchr.o

# target to build an object file
libft/ft_strrchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrchr.c.o
.PHONY : libft/ft_strrchr.c.o

libft/ft_strrchr.i: libft/ft_strrchr.c.i
.PHONY : libft/ft_strrchr.i

# target to preprocess a source file
libft/ft_strrchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrchr.c.i
.PHONY : libft/ft_strrchr.c.i

libft/ft_strrchr.s: libft/ft_strrchr.c.s
.PHONY : libft/ft_strrchr.s

# target to generate assembly for a file
libft/ft_strrchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrchr.c.s
.PHONY : libft/ft_strrchr.c.s

libft/ft_strrepl.o: libft/ft_strrepl.c.o
.PHONY : libft/ft_strrepl.o

# target to build an object file
libft/ft_strrepl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrepl.c.o
.PHONY : libft/ft_strrepl.c.o

libft/ft_strrepl.i: libft/ft_strrepl.c.i
.PHONY : libft/ft_strrepl.i

# target to preprocess a source file
libft/ft_strrepl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrepl.c.i
.PHONY : libft/ft_strrepl.c.i

libft/ft_strrepl.s: libft/ft_strrepl.c.s
.PHONY : libft/ft_strrepl.s

# target to generate assembly for a file
libft/ft_strrepl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strrepl.c.s
.PHONY : libft/ft_strrepl.c.s

libft/ft_strtrim.o: libft/ft_strtrim.c.o
.PHONY : libft/ft_strtrim.o

# target to build an object file
libft/ft_strtrim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strtrim.c.o
.PHONY : libft/ft_strtrim.c.o

libft/ft_strtrim.i: libft/ft_strtrim.c.i
.PHONY : libft/ft_strtrim.i

# target to preprocess a source file
libft/ft_strtrim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strtrim.c.i
.PHONY : libft/ft_strtrim.c.i

libft/ft_strtrim.s: libft/ft_strtrim.c.s
.PHONY : libft/ft_strtrim.s

# target to generate assembly for a file
libft/ft_strtrim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_strtrim.c.s
.PHONY : libft/ft_strtrim.c.s

libft/ft_substr.o: libft/ft_substr.c.o
.PHONY : libft/ft_substr.o

# target to build an object file
libft/ft_substr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_substr.c.o
.PHONY : libft/ft_substr.c.o

libft/ft_substr.i: libft/ft_substr.c.i
.PHONY : libft/ft_substr.i

# target to preprocess a source file
libft/ft_substr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_substr.c.i
.PHONY : libft/ft_substr.c.i

libft/ft_substr.s: libft/ft_substr.c.s
.PHONY : libft/ft_substr.s

# target to generate assembly for a file
libft/ft_substr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_substr.c.s
.PHONY : libft/ft_substr.c.s

libft/ft_tolower.o: libft/ft_tolower.c.o
.PHONY : libft/ft_tolower.o

# target to build an object file
libft/ft_tolower.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_tolower.c.o
.PHONY : libft/ft_tolower.c.o

libft/ft_tolower.i: libft/ft_tolower.c.i
.PHONY : libft/ft_tolower.i

# target to preprocess a source file
libft/ft_tolower.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_tolower.c.i
.PHONY : libft/ft_tolower.c.i

libft/ft_tolower.s: libft/ft_tolower.c.s
.PHONY : libft/ft_tolower.s

# target to generate assembly for a file
libft/ft_tolower.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_tolower.c.s
.PHONY : libft/ft_tolower.c.s

libft/ft_toupper.o: libft/ft_toupper.c.o
.PHONY : libft/ft_toupper.o

# target to build an object file
libft/ft_toupper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_toupper.c.o
.PHONY : libft/ft_toupper.c.o

libft/ft_toupper.i: libft/ft_toupper.c.i
.PHONY : libft/ft_toupper.i

# target to preprocess a source file
libft/ft_toupper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_toupper.c.i
.PHONY : libft/ft_toupper.c.i

libft/ft_toupper.s: libft/ft_toupper.c.s
.PHONY : libft/ft_toupper.s

# target to generate assembly for a file
libft/ft_toupper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/ft_toupper.c.s
.PHONY : libft/ft_toupper.c.s

libft/get_next_line/get_next_line.o: libft/get_next_line/get_next_line.c.o
.PHONY : libft/get_next_line/get_next_line.o

# target to build an object file
libft/get_next_line/get_next_line.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line.c.o
.PHONY : libft/get_next_line/get_next_line.c.o

libft/get_next_line/get_next_line.i: libft/get_next_line/get_next_line.c.i
.PHONY : libft/get_next_line/get_next_line.i

# target to preprocess a source file
libft/get_next_line/get_next_line.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line.c.i
.PHONY : libft/get_next_line/get_next_line.c.i

libft/get_next_line/get_next_line.s: libft/get_next_line/get_next_line.c.s
.PHONY : libft/get_next_line/get_next_line.s

# target to generate assembly for a file
libft/get_next_line/get_next_line.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line.c.s
.PHONY : libft/get_next_line/get_next_line.c.s

libft/get_next_line/get_next_line_utils.o: libft/get_next_line/get_next_line_utils.c.o
.PHONY : libft/get_next_line/get_next_line_utils.o

# target to build an object file
libft/get_next_line/get_next_line_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line_utils.c.o
.PHONY : libft/get_next_line/get_next_line_utils.c.o

libft/get_next_line/get_next_line_utils.i: libft/get_next_line/get_next_line_utils.c.i
.PHONY : libft/get_next_line/get_next_line_utils.i

# target to preprocess a source file
libft/get_next_line/get_next_line_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line_utils.c.i
.PHONY : libft/get_next_line/get_next_line_utils.c.i

libft/get_next_line/get_next_line_utils.s: libft/get_next_line/get_next_line_utils.c.s
.PHONY : libft/get_next_line/get_next_line_utils.s

# target to generate assembly for a file
libft/get_next_line/get_next_line_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/get_next_line/get_next_line_utils.c.s
.PHONY : libft/get_next_line/get_next_line_utils.c.s

libft/len_array.o: libft/len_array.c.o
.PHONY : libft/len_array.o

# target to build an object file
libft/len_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/len_array.c.o
.PHONY : libft/len_array.c.o

libft/len_array.i: libft/len_array.c.i
.PHONY : libft/len_array.i

# target to preprocess a source file
libft/len_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/len_array.c.i
.PHONY : libft/len_array.c.i

libft/len_array.s: libft/len_array.c.s
.PHONY : libft/len_array.s

# target to generate assembly for a file
libft/len_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/len_array.c.s
.PHONY : libft/len_array.c.s

libft/list/ft_lstadd_back.o: libft/list/ft_lstadd_back.c.o
.PHONY : libft/list/ft_lstadd_back.o

# target to build an object file
libft/list/ft_lstadd_back.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_back.c.o
.PHONY : libft/list/ft_lstadd_back.c.o

libft/list/ft_lstadd_back.i: libft/list/ft_lstadd_back.c.i
.PHONY : libft/list/ft_lstadd_back.i

# target to preprocess a source file
libft/list/ft_lstadd_back.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_back.c.i
.PHONY : libft/list/ft_lstadd_back.c.i

libft/list/ft_lstadd_back.s: libft/list/ft_lstadd_back.c.s
.PHONY : libft/list/ft_lstadd_back.s

# target to generate assembly for a file
libft/list/ft_lstadd_back.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_back.c.s
.PHONY : libft/list/ft_lstadd_back.c.s

libft/list/ft_lstadd_front.o: libft/list/ft_lstadd_front.c.o
.PHONY : libft/list/ft_lstadd_front.o

# target to build an object file
libft/list/ft_lstadd_front.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_front.c.o
.PHONY : libft/list/ft_lstadd_front.c.o

libft/list/ft_lstadd_front.i: libft/list/ft_lstadd_front.c.i
.PHONY : libft/list/ft_lstadd_front.i

# target to preprocess a source file
libft/list/ft_lstadd_front.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_front.c.i
.PHONY : libft/list/ft_lstadd_front.c.i

libft/list/ft_lstadd_front.s: libft/list/ft_lstadd_front.c.s
.PHONY : libft/list/ft_lstadd_front.s

# target to generate assembly for a file
libft/list/ft_lstadd_front.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstadd_front.c.s
.PHONY : libft/list/ft_lstadd_front.c.s

libft/list/ft_lstclear.o: libft/list/ft_lstclear.c.o
.PHONY : libft/list/ft_lstclear.o

# target to build an object file
libft/list/ft_lstclear.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstclear.c.o
.PHONY : libft/list/ft_lstclear.c.o

libft/list/ft_lstclear.i: libft/list/ft_lstclear.c.i
.PHONY : libft/list/ft_lstclear.i

# target to preprocess a source file
libft/list/ft_lstclear.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstclear.c.i
.PHONY : libft/list/ft_lstclear.c.i

libft/list/ft_lstclear.s: libft/list/ft_lstclear.c.s
.PHONY : libft/list/ft_lstclear.s

# target to generate assembly for a file
libft/list/ft_lstclear.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstclear.c.s
.PHONY : libft/list/ft_lstclear.c.s

libft/list/ft_lstdelone.o: libft/list/ft_lstdelone.c.o
.PHONY : libft/list/ft_lstdelone.o

# target to build an object file
libft/list/ft_lstdelone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstdelone.c.o
.PHONY : libft/list/ft_lstdelone.c.o

libft/list/ft_lstdelone.i: libft/list/ft_lstdelone.c.i
.PHONY : libft/list/ft_lstdelone.i

# target to preprocess a source file
libft/list/ft_lstdelone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstdelone.c.i
.PHONY : libft/list/ft_lstdelone.c.i

libft/list/ft_lstdelone.s: libft/list/ft_lstdelone.c.s
.PHONY : libft/list/ft_lstdelone.s

# target to generate assembly for a file
libft/list/ft_lstdelone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstdelone.c.s
.PHONY : libft/list/ft_lstdelone.c.s

libft/list/ft_lstiter.o: libft/list/ft_lstiter.c.o
.PHONY : libft/list/ft_lstiter.o

# target to build an object file
libft/list/ft_lstiter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstiter.c.o
.PHONY : libft/list/ft_lstiter.c.o

libft/list/ft_lstiter.i: libft/list/ft_lstiter.c.i
.PHONY : libft/list/ft_lstiter.i

# target to preprocess a source file
libft/list/ft_lstiter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstiter.c.i
.PHONY : libft/list/ft_lstiter.c.i

libft/list/ft_lstiter.s: libft/list/ft_lstiter.c.s
.PHONY : libft/list/ft_lstiter.s

# target to generate assembly for a file
libft/list/ft_lstiter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstiter.c.s
.PHONY : libft/list/ft_lstiter.c.s

libft/list/ft_lstlast.o: libft/list/ft_lstlast.c.o
.PHONY : libft/list/ft_lstlast.o

# target to build an object file
libft/list/ft_lstlast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstlast.c.o
.PHONY : libft/list/ft_lstlast.c.o

libft/list/ft_lstlast.i: libft/list/ft_lstlast.c.i
.PHONY : libft/list/ft_lstlast.i

# target to preprocess a source file
libft/list/ft_lstlast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstlast.c.i
.PHONY : libft/list/ft_lstlast.c.i

libft/list/ft_lstlast.s: libft/list/ft_lstlast.c.s
.PHONY : libft/list/ft_lstlast.s

# target to generate assembly for a file
libft/list/ft_lstlast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstlast.c.s
.PHONY : libft/list/ft_lstlast.c.s

libft/list/ft_lstmap.o: libft/list/ft_lstmap.c.o
.PHONY : libft/list/ft_lstmap.o

# target to build an object file
libft/list/ft_lstmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstmap.c.o
.PHONY : libft/list/ft_lstmap.c.o

libft/list/ft_lstmap.i: libft/list/ft_lstmap.c.i
.PHONY : libft/list/ft_lstmap.i

# target to preprocess a source file
libft/list/ft_lstmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstmap.c.i
.PHONY : libft/list/ft_lstmap.c.i

libft/list/ft_lstmap.s: libft/list/ft_lstmap.c.s
.PHONY : libft/list/ft_lstmap.s

# target to generate assembly for a file
libft/list/ft_lstmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstmap.c.s
.PHONY : libft/list/ft_lstmap.c.s

libft/list/ft_lstnew.o: libft/list/ft_lstnew.c.o
.PHONY : libft/list/ft_lstnew.o

# target to build an object file
libft/list/ft_lstnew.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstnew.c.o
.PHONY : libft/list/ft_lstnew.c.o

libft/list/ft_lstnew.i: libft/list/ft_lstnew.c.i
.PHONY : libft/list/ft_lstnew.i

# target to preprocess a source file
libft/list/ft_lstnew.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstnew.c.i
.PHONY : libft/list/ft_lstnew.c.i

libft/list/ft_lstnew.s: libft/list/ft_lstnew.c.s
.PHONY : libft/list/ft_lstnew.s

# target to generate assembly for a file
libft/list/ft_lstnew.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstnew.c.s
.PHONY : libft/list/ft_lstnew.c.s

libft/list/ft_lstsize.o: libft/list/ft_lstsize.c.o
.PHONY : libft/list/ft_lstsize.o

# target to build an object file
libft/list/ft_lstsize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstsize.c.o
.PHONY : libft/list/ft_lstsize.c.o

libft/list/ft_lstsize.i: libft/list/ft_lstsize.c.i
.PHONY : libft/list/ft_lstsize.i

# target to preprocess a source file
libft/list/ft_lstsize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstsize.c.i
.PHONY : libft/list/ft_lstsize.c.i

libft/list/ft_lstsize.s: libft/list/ft_lstsize.c.s
.PHONY : libft/list/ft_lstsize.s

# target to generate assembly for a file
libft/list/ft_lstsize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/list/ft_lstsize.c.s
.PHONY : libft/list/ft_lstsize.c.s

libft/string/ft_string.o: libft/string/ft_string.c.o
.PHONY : libft/string/ft_string.o

# target to build an object file
libft/string/ft_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string.c.o
.PHONY : libft/string/ft_string.c.o

libft/string/ft_string.i: libft/string/ft_string.c.i
.PHONY : libft/string/ft_string.i

# target to preprocess a source file
libft/string/ft_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string.c.i
.PHONY : libft/string/ft_string.c.i

libft/string/ft_string.s: libft/string/ft_string.c.s
.PHONY : libft/string/ft_string.s

# target to generate assembly for a file
libft/string/ft_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string.c.s
.PHONY : libft/string/ft_string.c.s

libft/string/ft_string_append.o: libft/string/ft_string_append.c.o
.PHONY : libft/string/ft_string_append.o

# target to build an object file
libft/string/ft_string_append.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_append.c.o
.PHONY : libft/string/ft_string_append.c.o

libft/string/ft_string_append.i: libft/string/ft_string_append.c.i
.PHONY : libft/string/ft_string_append.i

# target to preprocess a source file
libft/string/ft_string_append.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_append.c.i
.PHONY : libft/string/ft_string_append.c.i

libft/string/ft_string_append.s: libft/string/ft_string_append.c.s
.PHONY : libft/string/ft_string_append.s

# target to generate assembly for a file
libft/string/ft_string_append.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_append.c.s
.PHONY : libft/string/ft_string_append.c.s

libft/string/ft_string_operations.o: libft/string/ft_string_operations.c.o
.PHONY : libft/string/ft_string_operations.o

# target to build an object file
libft/string/ft_string_operations.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_operations.c.o
.PHONY : libft/string/ft_string_operations.c.o

libft/string/ft_string_operations.i: libft/string/ft_string_operations.c.i
.PHONY : libft/string/ft_string_operations.i

# target to preprocess a source file
libft/string/ft_string_operations.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_operations.c.i
.PHONY : libft/string/ft_string_operations.c.i

libft/string/ft_string_operations.s: libft/string/ft_string_operations.c.s
.PHONY : libft/string/ft_string_operations.s

# target to generate assembly for a file
libft/string/ft_string_operations.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_operations.c.s
.PHONY : libft/string/ft_string_operations.c.s

libft/string/ft_string_util.o: libft/string/ft_string_util.c.o
.PHONY : libft/string/ft_string_util.o

# target to build an object file
libft/string/ft_string_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_util.c.o
.PHONY : libft/string/ft_string_util.c.o

libft/string/ft_string_util.i: libft/string/ft_string_util.c.i
.PHONY : libft/string/ft_string_util.i

# target to preprocess a source file
libft/string/ft_string_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_util.c.i
.PHONY : libft/string/ft_string_util.c.i

libft/string/ft_string_util.s: libft/string/ft_string_util.c.s
.PHONY : libft/string/ft_string_util.s

# target to generate assembly for a file
libft/string/ft_string_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/libft/string/ft_string_util.c.s
.PHONY : libft/string/ft_string_util.c.s

srcs/camera.o: srcs/camera.c.o
.PHONY : srcs/camera.o

# target to build an object file
srcs/camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/camera.c.o
.PHONY : srcs/camera.c.o

srcs/camera.i: srcs/camera.c.i
.PHONY : srcs/camera.i

# target to preprocess a source file
srcs/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/camera.c.i
.PHONY : srcs/camera.c.i

srcs/camera.s: srcs/camera.c.s
.PHONY : srcs/camera.s

# target to generate assembly for a file
srcs/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/camera.c.s
.PHONY : srcs/camera.c.s

srcs/color.o: srcs/color.c.o
.PHONY : srcs/color.o

# target to build an object file
srcs/color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/color.c.o
.PHONY : srcs/color.c.o

srcs/color.i: srcs/color.c.i
.PHONY : srcs/color.i

# target to preprocess a source file
srcs/color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/color.c.i
.PHONY : srcs/color.c.i

srcs/color.s: srcs/color.c.s
.PHONY : srcs/color.s

# target to generate assembly for a file
srcs/color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/color.c.s
.PHONY : srcs/color.c.s

srcs/coords.o: srcs/coords.c.o
.PHONY : srcs/coords.o

# target to build an object file
srcs/coords.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/coords.c.o
.PHONY : srcs/coords.c.o

srcs/coords.i: srcs/coords.c.i
.PHONY : srcs/coords.i

# target to preprocess a source file
srcs/coords.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/coords.c.i
.PHONY : srcs/coords.c.i

srcs/coords.s: srcs/coords.c.s
.PHONY : srcs/coords.s

# target to generate assembly for a file
srcs/coords.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/coords.c.s
.PHONY : srcs/coords.c.s

srcs/miniRT.o: srcs/miniRT.c.o
.PHONY : srcs/miniRT.o

# target to build an object file
srcs/miniRT.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/miniRT.c.o
.PHONY : srcs/miniRT.c.o

srcs/miniRT.i: srcs/miniRT.c.i
.PHONY : srcs/miniRT.i

# target to preprocess a source file
srcs/miniRT.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/miniRT.c.i
.PHONY : srcs/miniRT.c.i

srcs/miniRT.s: srcs/miniRT.c.s
.PHONY : srcs/miniRT.s

# target to generate assembly for a file
srcs/miniRT.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/miniRT.c.s
.PHONY : srcs/miniRT.c.s

srcs/parsing/parse_ACL.o: srcs/parsing/parse_ACL.c.o
.PHONY : srcs/parsing/parse_ACL.o

# target to build an object file
srcs/parsing/parse_ACL.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_ACL.c.o
.PHONY : srcs/parsing/parse_ACL.c.o

srcs/parsing/parse_ACL.i: srcs/parsing/parse_ACL.c.i
.PHONY : srcs/parsing/parse_ACL.i

# target to preprocess a source file
srcs/parsing/parse_ACL.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_ACL.c.i
.PHONY : srcs/parsing/parse_ACL.c.i

srcs/parsing/parse_ACL.s: srcs/parsing/parse_ACL.c.s
.PHONY : srcs/parsing/parse_ACL.s

# target to generate assembly for a file
srcs/parsing/parse_ACL.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_ACL.c.s
.PHONY : srcs/parsing/parse_ACL.c.s

srcs/parsing/parse_file.o: srcs/parsing/parse_file.c.o
.PHONY : srcs/parsing/parse_file.o

# target to build an object file
srcs/parsing/parse_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_file.c.o
.PHONY : srcs/parsing/parse_file.c.o

srcs/parsing/parse_file.i: srcs/parsing/parse_file.c.i
.PHONY : srcs/parsing/parse_file.i

# target to preprocess a source file
srcs/parsing/parse_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_file.c.i
.PHONY : srcs/parsing/parse_file.c.i

srcs/parsing/parse_file.s: srcs/parsing/parse_file.c.s
.PHONY : srcs/parsing/parse_file.s

# target to generate assembly for a file
srcs/parsing/parse_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_file.c.s
.PHONY : srcs/parsing/parse_file.c.s

srcs/parsing/parse_lines.o: srcs/parsing/parse_lines.c.o
.PHONY : srcs/parsing/parse_lines.o

# target to build an object file
srcs/parsing/parse_lines.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_lines.c.o
.PHONY : srcs/parsing/parse_lines.c.o

srcs/parsing/parse_lines.i: srcs/parsing/parse_lines.c.i
.PHONY : srcs/parsing/parse_lines.i

# target to preprocess a source file
srcs/parsing/parse_lines.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_lines.c.i
.PHONY : srcs/parsing/parse_lines.c.i

srcs/parsing/parse_lines.s: srcs/parsing/parse_lines.c.s
.PHONY : srcs/parsing/parse_lines.s

# target to generate assembly for a file
srcs/parsing/parse_lines.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_lines.c.s
.PHONY : srcs/parsing/parse_lines.c.s

srcs/parsing/parse_plspcy.o: srcs/parsing/parse_plspcy.c.o
.PHONY : srcs/parsing/parse_plspcy.o

# target to build an object file
srcs/parsing/parse_plspcy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_plspcy.c.o
.PHONY : srcs/parsing/parse_plspcy.c.o

srcs/parsing/parse_plspcy.i: srcs/parsing/parse_plspcy.c.i
.PHONY : srcs/parsing/parse_plspcy.i

# target to preprocess a source file
srcs/parsing/parse_plspcy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_plspcy.c.i
.PHONY : srcs/parsing/parse_plspcy.c.i

srcs/parsing/parse_plspcy.s: srcs/parsing/parse_plspcy.c.s
.PHONY : srcs/parsing/parse_plspcy.s

# target to generate assembly for a file
srcs/parsing/parse_plspcy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/parsing/parse_plspcy.c.s
.PHONY : srcs/parsing/parse_plspcy.c.s

srcs/util.o: srcs/util.c.o
.PHONY : srcs/util.o

# target to build an object file
srcs/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/util.c.o
.PHONY : srcs/util.c.o

srcs/util.i: srcs/util.c.i
.PHONY : srcs/util.i

# target to preprocess a source file
srcs/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/util.c.i
.PHONY : srcs/util.c.i

srcs/util.s: srcs/util.c.s
.PHONY : srcs/util.s

# target to generate assembly for a file
srcs/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/util.c.s
.PHONY : srcs/util.c.s

srcs/vectors.o: srcs/vectors.c.o
.PHONY : srcs/vectors.o

# target to build an object file
srcs/vectors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/vectors.c.o
.PHONY : srcs/vectors.c.o

srcs/vectors.i: srcs/vectors.c.i
.PHONY : srcs/vectors.i

# target to preprocess a source file
srcs/vectors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/vectors.c.i
.PHONY : srcs/vectors.c.i

srcs/vectors.s: srcs/vectors.c.s
.PHONY : srcs/vectors.s

# target to generate assembly for a file
srcs/vectors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/srcs/vectors.c.s
.PHONY : srcs/vectors.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... miniRT"
	@echo "... libft/free_array.o"
	@echo "... libft/free_array.i"
	@echo "... libft/free_array.s"
	@echo "... libft/ft_atod.o"
	@echo "... libft/ft_atod.i"
	@echo "... libft/ft_atod.s"
	@echo "... libft/ft_atoi.o"
	@echo "... libft/ft_atoi.i"
	@echo "... libft/ft_atoi.s"
	@echo "... libft/ft_bzero.o"
	@echo "... libft/ft_bzero.i"
	@echo "... libft/ft_bzero.s"
	@echo "... libft/ft_calloc.o"
	@echo "... libft/ft_calloc.i"
	@echo "... libft/ft_calloc.s"
	@echo "... libft/ft_contains.o"
	@echo "... libft/ft_contains.i"
	@echo "... libft/ft_contains.s"
	@echo "... libft/ft_ends_with.o"
	@echo "... libft/ft_ends_with.i"
	@echo "... libft/ft_ends_with.s"
	@echo "... libft/ft_isalnum.o"
	@echo "... libft/ft_isalnum.i"
	@echo "... libft/ft_isalnum.s"
	@echo "... libft/ft_isalpha.o"
	@echo "... libft/ft_isalpha.i"
	@echo "... libft/ft_isalpha.s"
	@echo "... libft/ft_isascii.o"
	@echo "... libft/ft_isascii.i"
	@echo "... libft/ft_isascii.s"
	@echo "... libft/ft_isdigit.o"
	@echo "... libft/ft_isdigit.i"
	@echo "... libft/ft_isdigit.s"
	@echo "... libft/ft_isprint.o"
	@echo "... libft/ft_isprint.i"
	@echo "... libft/ft_isprint.s"
	@echo "... libft/ft_iswhite_space.o"
	@echo "... libft/ft_iswhite_space.i"
	@echo "... libft/ft_iswhite_space.s"
	@echo "... libft/ft_itoa.o"
	@echo "... libft/ft_itoa.i"
	@echo "... libft/ft_itoa.s"
	@echo "... libft/ft_memchr.o"
	@echo "... libft/ft_memchr.i"
	@echo "... libft/ft_memchr.s"
	@echo "... libft/ft_memcmp.o"
	@echo "... libft/ft_memcmp.i"
	@echo "... libft/ft_memcmp.s"
	@echo "... libft/ft_memcpy.o"
	@echo "... libft/ft_memcpy.i"
	@echo "... libft/ft_memcpy.s"
	@echo "... libft/ft_memmove.o"
	@echo "... libft/ft_memmove.i"
	@echo "... libft/ft_memmove.s"
	@echo "... libft/ft_memset.o"
	@echo "... libft/ft_memset.i"
	@echo "... libft/ft_memset.s"
	@echo "... libft/ft_printf/ft_printf.o"
	@echo "... libft/ft_printf/ft_printf.i"
	@echo "... libft/ft_printf/ft_printf.s"
	@echo "... libft/ft_printf/hex.o"
	@echo "... libft/ft_printf/hex.i"
	@echo "... libft/ft_printf/hex.s"
	@echo "... libft/ft_printf/hex_util.o"
	@echo "... libft/ft_printf/hex_util.i"
	@echo "... libft/ft_printf/hex_util.s"
	@echo "... libft/ft_printf/printing.o"
	@echo "... libft/ft_printf/printing.i"
	@echo "... libft/ft_printf/printing.s"
	@echo "... libft/ft_putchar_fd.o"
	@echo "... libft/ft_putchar_fd.i"
	@echo "... libft/ft_putchar_fd.s"
	@echo "... libft/ft_putendl_fd.o"
	@echo "... libft/ft_putendl_fd.i"
	@echo "... libft/ft_putendl_fd.s"
	@echo "... libft/ft_putnbr_fd.o"
	@echo "... libft/ft_putnbr_fd.i"
	@echo "... libft/ft_putnbr_fd.s"
	@echo "... libft/ft_putstr_fd.o"
	@echo "... libft/ft_putstr_fd.i"
	@echo "... libft/ft_putstr_fd.s"
	@echo "... libft/ft_split.o"
	@echo "... libft/ft_split.i"
	@echo "... libft/ft_split.s"
	@echo "... libft/ft_starts_with.o"
	@echo "... libft/ft_starts_with.i"
	@echo "... libft/ft_starts_with.s"
	@echo "... libft/ft_strchr.o"
	@echo "... libft/ft_strchr.i"
	@echo "... libft/ft_strchr.s"
	@echo "... libft/ft_strdup.o"
	@echo "... libft/ft_strdup.i"
	@echo "... libft/ft_strdup.s"
	@echo "... libft/ft_streq.o"
	@echo "... libft/ft_streq.i"
	@echo "... libft/ft_streq.s"
	@echo "... libft/ft_striteri.o"
	@echo "... libft/ft_striteri.i"
	@echo "... libft/ft_striteri.s"
	@echo "... libft/ft_strjoin.o"
	@echo "... libft/ft_strjoin.i"
	@echo "... libft/ft_strjoin.s"
	@echo "... libft/ft_strlcat.o"
	@echo "... libft/ft_strlcat.i"
	@echo "... libft/ft_strlcat.s"
	@echo "... libft/ft_strlcpy.o"
	@echo "... libft/ft_strlcpy.i"
	@echo "... libft/ft_strlcpy.s"
	@echo "... libft/ft_strlen.o"
	@echo "... libft/ft_strlen.i"
	@echo "... libft/ft_strlen.s"
	@echo "... libft/ft_strmapi.o"
	@echo "... libft/ft_strmapi.i"
	@echo "... libft/ft_strmapi.s"
	@echo "... libft/ft_strncmp.o"
	@echo "... libft/ft_strncmp.i"
	@echo "... libft/ft_strncmp.s"
	@echo "... libft/ft_strnstr.o"
	@echo "... libft/ft_strnstr.i"
	@echo "... libft/ft_strnstr.s"
	@echo "... libft/ft_strrchr.o"
	@echo "... libft/ft_strrchr.i"
	@echo "... libft/ft_strrchr.s"
	@echo "... libft/ft_strrepl.o"
	@echo "... libft/ft_strrepl.i"
	@echo "... libft/ft_strrepl.s"
	@echo "... libft/ft_strtrim.o"
	@echo "... libft/ft_strtrim.i"
	@echo "... libft/ft_strtrim.s"
	@echo "... libft/ft_substr.o"
	@echo "... libft/ft_substr.i"
	@echo "... libft/ft_substr.s"
	@echo "... libft/ft_tolower.o"
	@echo "... libft/ft_tolower.i"
	@echo "... libft/ft_tolower.s"
	@echo "... libft/ft_toupper.o"
	@echo "... libft/ft_toupper.i"
	@echo "... libft/ft_toupper.s"
	@echo "... libft/get_next_line/get_next_line.o"
	@echo "... libft/get_next_line/get_next_line.i"
	@echo "... libft/get_next_line/get_next_line.s"
	@echo "... libft/get_next_line/get_next_line_utils.o"
	@echo "... libft/get_next_line/get_next_line_utils.i"
	@echo "... libft/get_next_line/get_next_line_utils.s"
	@echo "... libft/len_array.o"
	@echo "... libft/len_array.i"
	@echo "... libft/len_array.s"
	@echo "... libft/list/ft_lstadd_back.o"
	@echo "... libft/list/ft_lstadd_back.i"
	@echo "... libft/list/ft_lstadd_back.s"
	@echo "... libft/list/ft_lstadd_front.o"
	@echo "... libft/list/ft_lstadd_front.i"
	@echo "... libft/list/ft_lstadd_front.s"
	@echo "... libft/list/ft_lstclear.o"
	@echo "... libft/list/ft_lstclear.i"
	@echo "... libft/list/ft_lstclear.s"
	@echo "... libft/list/ft_lstdelone.o"
	@echo "... libft/list/ft_lstdelone.i"
	@echo "... libft/list/ft_lstdelone.s"
	@echo "... libft/list/ft_lstiter.o"
	@echo "... libft/list/ft_lstiter.i"
	@echo "... libft/list/ft_lstiter.s"
	@echo "... libft/list/ft_lstlast.o"
	@echo "... libft/list/ft_lstlast.i"
	@echo "... libft/list/ft_lstlast.s"
	@echo "... libft/list/ft_lstmap.o"
	@echo "... libft/list/ft_lstmap.i"
	@echo "... libft/list/ft_lstmap.s"
	@echo "... libft/list/ft_lstnew.o"
	@echo "... libft/list/ft_lstnew.i"
	@echo "... libft/list/ft_lstnew.s"
	@echo "... libft/list/ft_lstsize.o"
	@echo "... libft/list/ft_lstsize.i"
	@echo "... libft/list/ft_lstsize.s"
	@echo "... libft/string/ft_string.o"
	@echo "... libft/string/ft_string.i"
	@echo "... libft/string/ft_string.s"
	@echo "... libft/string/ft_string_append.o"
	@echo "... libft/string/ft_string_append.i"
	@echo "... libft/string/ft_string_append.s"
	@echo "... libft/string/ft_string_operations.o"
	@echo "... libft/string/ft_string_operations.i"
	@echo "... libft/string/ft_string_operations.s"
	@echo "... libft/string/ft_string_util.o"
	@echo "... libft/string/ft_string_util.i"
	@echo "... libft/string/ft_string_util.s"
	@echo "... srcs/camera.o"
	@echo "... srcs/camera.i"
	@echo "... srcs/camera.s"
	@echo "... srcs/color.o"
	@echo "... srcs/color.i"
	@echo "... srcs/color.s"
	@echo "... srcs/coords.o"
	@echo "... srcs/coords.i"
	@echo "... srcs/coords.s"
	@echo "... srcs/miniRT.o"
	@echo "... srcs/miniRT.i"
	@echo "... srcs/miniRT.s"
	@echo "... srcs/parsing/parse_ACL.o"
	@echo "... srcs/parsing/parse_ACL.i"
	@echo "... srcs/parsing/parse_ACL.s"
	@echo "... srcs/parsing/parse_file.o"
	@echo "... srcs/parsing/parse_file.i"
	@echo "... srcs/parsing/parse_file.s"
	@echo "... srcs/parsing/parse_lines.o"
	@echo "... srcs/parsing/parse_lines.i"
	@echo "... srcs/parsing/parse_lines.s"
	@echo "... srcs/parsing/parse_plspcy.o"
	@echo "... srcs/parsing/parse_plspcy.i"
	@echo "... srcs/parsing/parse_plspcy.s"
	@echo "... srcs/util.o"
	@echo "... srcs/util.i"
	@echo "... srcs/util.s"
	@echo "... srcs/vectors.o"
	@echo "... srcs/vectors.i"
	@echo "... srcs/vectors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

